### ISSUE TITLE
Whitespace in locale files

### ISSUE THREAD

**Issue by Wuzzy2** [mt-mods/unifieddyes#11]
I've found errors in `unifieddyes.tr.tr` and `template.txt`.

The first one has some whitespace-only lines, which is not allowed if I understand `lua_api.txt` correctly (the lines should be completely empty instead).

The second one has whitespace after the equals signs.

Solution: Delete all whitespace in these files.

Found with this script: https://codeberg.org/Wuzzy/minetest_check_translations

Version: 2022-09-12

**Comment by wsor4035** [comment]
What actual errors does it cause other than formating? You fail to mention this while your issue instead looks like an advert for your tool

**Comment by Wuzzy2** [comment]
As I said, the lua_api.txt definition only explicitly permits empty lines, comment lines, translation lines and textdomain lines. So the way I interpret this document is that whitespace-only lines are technically a syntax error.

Look, I was just trying to help. Just close this issue if you disagree.

Also: "advert for my tool"? ... oh, come on!

**Comment by wsor4035** [comment]
so nothing is actually broken, just syntax stuff that according to your interpretation of the docs might be wrong.

**Comment by Wuzzy2** [comment]
I don't know if it breaks with current Minetest. At least I did not experience a crash so far. Anyway, I just follow the docs. If the docs would say that whitespace is OK, I would update things accordingly. But yeah, it's probably less serious than, let's say, a malformed escape sequence. So I agree with the low priority.

**Comment by Wuzzy2** [comment]
FYI, this is the reason why I posted this:

> The file should be a text file, with the following format:
> 
> * Lines beginning with `# textdomain:` (the space is significant) can be used
>   to specify the text domain of all following translations in the file.
> * All other empty lines or lines beginning with `#` are ignored.
> * Other lines should be in the format `original=translated`. Both `original`
>   and `translated` can contain escape sequences beginning with `@` to insert
>   arguments, literal `@`, `=` or newline (See [Escapes] below).
>   There must be no extraneous whitespace around the `=` or at the beginning or
>   the end of the line.

So the docs seem to say nothing about whitespace-only lines. Only "empty lines". So a whitespace-only line is neither officially part of the syntax nor explicitly forbidden. So this means a whitespace-only line is undefined behavior then, I guess. Maybe the real fix is to update the docs. \*shrug\*
