### ISSUE TITLE
Missing `digger == nil` check in `node_dig_without_color()`

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/unifieddyes#20]
See https://github.com/minetest/minetest/issues/14553#issuecomment-2064697025 and https://github.com/mt-mods/unifieddyes/commit/5af9254c3a98f086be7fcfd0ba479aea133ea41e#r141122389

**Comment by jamesreqiuem** [comment]
Do you think there is a way to fix the error so that I can log into the world again? Or is the world lost?

**Comment by wsor4035** [comment]
> Do you think there is a way to fix the error so that I can log into the world again? Or is the world lost?

yeah, a fix will be made here and then youll need to update the mod once thats done
