### ISSUE TITLE
Need to allow airbrushing of default wool

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/unifieddyes#3]
Need to allow airbrushing of default wool
TSIA
@VanessaE

**Comment by SwissalpS** [comment]
I actually like that wool is different in that it can't be painted using param2. Makes it more impressive when somebody makes nice art using wool instead of scifi plastic and the others that are paintbrushable. Clay has both, a set of fixed nodes and then the paintbrushable variant.

**Comment by wsor4035** [comment]
closing this as it is better to have a external mod do this (most items that work with unified dyes are via a external mod or built into that mod - see colored wood, etc) and also is less game specific things built into the mod
